In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view

In [2]:
mp_key = "7T8Rm9ppE58YHsBs2IkJCMwMXshrwbpx"
mp_id = "mp-1018096"

In [3]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# Première symétrie

In [4]:
s1 = SymmOp.from_xyz_str('-y-1/3,x-y+1/3,z+1/3')
print(s1)

Rot:
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[-0.33333333  0.33333333  0.33333333]


Concentrons-nous d'abord sur le point (2/3, 1/3, 1/3) de la maille conventionnelle. Il correspond à un ion $\text{F}^{-}$. Nous voulons lui appliquer une rotation hélicoïdal $3_{\frac{1}{3}}$.

Sa matrice de rotation $R$ et son vecteur de translation $\tau$ sont donnés par :

$R = 
\begin{pmatrix}
0 & -1 & 0 \\
1 & -1 & 0 \\
0 & 0 & 1
\end{pmatrix}
$

$
\tau = 
\begin{pmatrix}
-1/3 \\
1/3 \\
1/3
\end{pmatrix}
$


In [5]:
s1.operate([2/3, 1/3, 1/3])

array([-0.66666667,  0.66666667,  0.66666667])

Après avoir appliqué l'opération de symétrie, nous obtenons le point (-2/3, 2/3, 2/3) équivalent au point (1/3, 2/3, 2/3) (grâce à la périodicité du réseau). Visuellement, cela donne :

In [17]:
view = quick_view(prim_struc, "packed", conventional=True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [18]:
view.script('select barium; color gold')
view.script('select nitrogen; color blue')
view.script('select fluorine; color red')
view.script("draw symop '-y-1/3,x-y+1/3,z+1/3' {2/3,1/3,1/3}")

# Deuxième symétrie

In [8]:
s2 = SymmOp.from_xyz_str('-x-1/3,-y+1/3,-z+1/3')
print(s2)

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[-0.33333333  0.33333333  0.33333333]


Etudions maintenant le point (0.66666667, 0.33333333, 0.57569332). Il s'agit d'un ion $\text{Ba}^{2+}$. Nous voulons lui appliquer une opération $\bar{1}$ de centre  (-1/6, 1/6, 1/6), c.-à-d. une rotoinversion d'ordre 1 avec un centre d'inversion en (-1/6, 1/6, 1/6).

La matrice de rotation $R$ et le vecteur de translation $\tau$ associés sont donnés par :

$R = 
\begin{pmatrix}
-1 & 0 & 0 \\
1 & -1 & 0 \\
0 & 0 & -1
\end{pmatrix}
$

$
\tau = 
\begin{pmatrix}
-1/3 \\
1/3 \\
1/3
\end{pmatrix}
$

In [9]:
s2.operate([0.66666667, 0.33333333, 0.57569332])

array([-1.00000000e+00,  3.33333333e-09, -2.42359987e-01])

Après avoir appliqué l'opération de symétrie, nous obtenons le point (-1.00000000e+00,  3.33333333e-09, -2.42359987e-01), qui correspond, de par la périodicité en translation du réseau, au point (0, 0, 0.75764002).

Visuellement, cela donne :

In [19]:
view = quick_view(prim_struc, "packed", conventional=True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [20]:
view.script('select barium; color gold')
view.script('select nitrogen; color blue')
view.script('select fluorine; color red')
view.script("draw symop '-x-1/3,-y+1/3,-z+1/3' {atomindex=8}")

# Troisième symétrie

In [12]:
s3 = SymmOp.from_xyz_str('-y,x-y,z')
print(s3)

Rot:
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


Etudions à présent l'ion $\text{N}^{3-}$ en (0, 1, 1/2). Appliquons-lui une rotation d'ordre 3.

La matrice de rotation $R$ associée est donnée par :

$R = 
\begin{pmatrix}
0 & -1 & 0 \\
1 & -1 & 0 \\
0 & 0 & 1
\end{pmatrix}
$

In [13]:
s3.operate([0, 1, 1/2])

array([-1. , -1. ,  0.5])

Après avoir appliqué la rotation, nous obtenons le point (-1, -1, 1/2) équivalent au point (0, 0, 1/2) (grâce à la périodicité du réseau). 

Visuellement, cela donne :

In [14]:
view = quick_view(prim_struc, "packed", conventional=True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [15]:
view.script('select barium; color gold')
view.script('select nitrogen; color blue')
view.script('select fluorine; color red')
view.script("draw symop '-y,x-y,z' {atomindex=16}")